### ISSUE TITLE
Please Update Your Site

### ISSUE THREAD

**Issue by Lilitheve** [AlphaOptix/bdocrystalz#5]
You had the best and easiest to use crystal site. Myself and many others would be grateful for a new update! BDDatabase and BDOCodex just don't have the simplicity of this site.

Please, please, PLEASE!!

**Comment by dynisor** [comment]
I will look into getting the site updated with the latest info for you as soon as I can. :)

**Comment by dynisor** [comment]
Sorry for the delay. It has been updated. :)
